name: Node CI

on: 
  push:
    branches: [master] 
  pull_request:
    branches: [master]
jobs:
  build:

    runs-on: ubuntu-latest
    environment: devSite
    env:        
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }} 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
     - uses: actions/checkout@v1
     - name: Install Node.js
       uses: actions/setup-node@v1
       with:
        node-version: '18.x'
     - name: Install npm dependencies
       run: npm install
     - name: Run build task
       run: npm run build
     - name: Deploy to Staging server
       uses: easingthemes/ssh-deploy@main
       env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: ".output/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
